### ISSUE TITLE
could not format html files

### ISSUE THREAD

**Issue by tiehan** [yihui/hugo-xmin#14]
I covert wordpress xml to md file with your tools "oldblog_xml", then I use blogdown to format html files, but can't format html files.

The MD file look like this, 
---
author: sam
comments: true
date: 2015-04-29 15:56:59+00:00
layout: post
link: http://hugo.qinqianshan.com/wordpress-display-page-plugins-pagenavi/
slug: wordpress-display-page-plugins-pagenavi
title: Wordpress显示分页--插件Pagenavi
wordpress_id: 14
categories:
- Wordpress
tags:
- Pagenavi
- wordpress
- 显示分页
---

If I remove " layout" and "slug" ,it will format html files. Because I have 400 md files, if I remove "layout" and "slug" one by one ,it will take long time . Do you have any suggestions to solve this ?

**Comment by yihui** [comment]
You can certainly modify YAML fields programmatically in a loop. See the last part of the section https://bookdown.org/yihui/blogdown/from-jekyll.html

**Comment by tiehan** [comment]
Thanks . If I  want to keep " layout" and "slug"  in  md files ,  and it can also format html files.  How to do ?

**Comment by yihui** [comment]
`slug` has nothing to do with the HTML format.

For `layout`, if you must use it, you have to understand more about Hugo templates: https://gohugo.io/templates/single-page-templates/

**Comment by tiehan** [comment]
Get it .Thanks very much !
