### ISSUE TITLE
how to add subcategories

### ISSUE THREAD

**Issue by tiehan** [yihui/hugo-xmin#15]
I like your hugo-xmin theme very much . I have many categories and some subcategories, how to add subcategories ?

**Comment by yihui** [comment]
I don't think Hugo supports nested categories.

**Comment by tiehan** [comment]
Thanks

**Comment by tiehan** [comment]
Now HUGO supports nested sections.
http://www.gohugo.org/doc/content/organization/

content organization like this
.
└── content
    ├── post
    |   ├── firstpost.md   // <- http://1.com/post/firstpost/
    |   ├── happy
    |   |   └── ness.md  // <- http://1.com/post/happy/ness/
    |   └── secondpost.md  // <- http://1.com/post/secondpost/
    └── quote
        ├── first.md       // <- http://1.com/quote/first/
        └── second.md      // <- http://1.com/quote/second/

And the question also be dissucssed ：
https://github.com/gohugoio/hugo/issues/465

I wonder how to show subsection in category or list 
（look like this :http://vjeantet.github.io/hugo-menu-show/）

**Comment by yihui** [comment]
Yes, I'm aware of nested sections: https://gohugo.io/content-management/sections/ There is not much documentation yet. This is pretty much all you can read and learn from: https://github.com/gohugoio/hugo/releases/tag/v0.22

**Comment by tiehan** [comment]
Thanks for your share . I see it and try to copy  bep's sections-tree.html to your xmin theme partial folder 

sections-tree.html:
{{ $home := .Site.Home }}
<div class="css-treeview box">
	<ul>
		<li><input type="checkbox" id="item-0" checked="checked" /><label for="item-0">Home</label>
		<ul>
		{{ template "section-tree-nav" $home }}
		</ul>
	</ul>
</div>

{{ define "section-tree-nav" }}

{{ range .Sections.Reverse}}
<li>
	<li><input type="checkbox" id="item-0-0" checked="checked"/><label for="item-0-0">{{ .Title }}</label>
	<ul>
		{{ range .Pages }}
		<li><a href="{{ .RelPermalink}}">{{ .Title }}</a></li>
		{{ end }}
		<ul>
		{{ template "section-tree-nav" . }}
		</ul>
	</ul>
</li>
</li>
{{ end }}
{{ end }}

and I put one cood in your xmin list.html

{{ partial "sections-tree.html" . }}

I find it do not work well . I think it is very hard for me to show nest sections in list.html.
