### ISSUE TITLE
Strange behavior of `build.R` under `R` directory

### ISSUE THREAD

**Issue by psychelzh** [yihui/hugo-xmin#20]
I found the script "build.R" will always create a `README.md` at the parent directory of my blog site project. I think it is because of the destination directory is used as `../README.md`, and in many conditions the working directory is the project root directory. So that command will then creat a `README.md` file at the parent directory of the project root directory, which is not intended.

```r
file.copy('content/_index.markdown', '../README.md', overwrite = TRUE)
if (Sys.which('sed') != '') system("sed -i '' -e '1,6d' -e '34,38d' ../README.md")
cat(
  '[![Screenshot](https://github.com/yihui/hugo-xmin/raw/master/images/screenshot.png)](https://xmin.yihui.name)\n',
  file = '../README.md', append = TRUE
)
```

**Comment by psychelzh** [comment]
And if I would like to write a `README.md` file independently, is it safe to delete these lines?

**Comment by yihui** [comment]
Yes.
