### ISSUE TITLE
create a post in .rmd format

### ISSUE THREAD

**Issue by XUKEREN** [yihui/hugo-xmin#27]
<img width="622" alt="screen shot 2018-03-25 at 12 24 25 pm" src="https://user-images.githubusercontent.com/37352799/37877336-aecf660c-3027-11e8-99d1-c6756e325da1.png">
Hi Yihui,
Thank you very much for creating the xmin theme. I am using it to create my personal website. As a newbie, I wasn't sure how to create a new post. 
I tried the addin in RStudio to create a .md format post, committed, and then pushed it to the github. The post in .md format has been successfully published on my website. 
However, when I used the same way to try to create a new post in .rmd format, it can't be shown on my website. I wonder if there are any other steps for creating a post in .rmd format? or we can only create a post in .md format? 
Thank you very much for your help!

Keren

**Comment by yihui** [comment]
https://bookdown.org/yihui/blogdown/workflow.html

**Comment by XUKEREN** [comment]
It works! I think I didn't serve site. 
<img width="158" alt="screen shot 2018-03-25 at 12 57 38 pm" src="https://user-images.githubusercontent.com/37352799/37877644-3d737e26-302c-11e8-94ed-80b1700ea9b5.png">

**Comment by yihui** [comment]
Correct.
