### ISSUE TITLE
Change Categories to Topics

### ISSUE THREAD

**Issue by AdamSadowski** [yihui/hugo-xmin#29]
Is it possible to change all instances of categories to topics? 

Thanks,
Adam

**Comment by yihui** [comment]
I think it should be possible, but I don't have time to help you with this specific task. Anyway, this theme only consists of 150 lines of code, which is fully documented in the blogdown book: https://bookdown.org/yihui/blogdown/templates.html

[You may have better luck on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/), or the [RStudio Community](https://community.rstudio.com).
