### ISSUE TITLE
How do I remove or limit the post list on the homepage

### ISSUE THREAD

**Issue by zayuim** [yihui/hugo-xmin#34]
The homepage of an xmin Hugo site contains a list of all posts under all pages. I have some old posts that I don't want to display on the homepage, I was wondering if it was possible to...

1) Limit what pages it includes posts from? (e.g. only include posts from "posts" and exclude "notes".)
2) Limit how long the list is? (probably the easiest?)
3) Remove it altogether?

I would want this to only affect the homepage's list and not to touch the pages own lists.

Thanks! :)

**Comment by leerichardson** [comment]
I am also looking to figure this out!

**Comment by yihui** [comment]
Sorry, I don't have time to answer your specific questions, but this theme has been explained line-by-line in the blogdown book: https://bookdown.org/yihui/blogdown/templates.html

**Comment by leerichardson** [comment]
Here's small hack to get rid of it completely (option #3) 

- In your themes sub-directory, edit the "themes/xmin/layouts/_default/list.html file, 
on lines 9-18, add an if-statement that skips the loop, if this is the home page:

{{if not .IsHome }}
<ul>
  {{ range (where .Data.Pages "Section" "!=" "") }}
  <li>
    <span class="date">{{ .Date.Format "2006/01/02" }}</span>
    <a href="{{ .URL }}">{{ .Title | markdownify }}</a>
  </li>
  {{ end }}
</ul>
{{ end }}

One thing I don't understand: How does Hugo decide which template to use, for each page? For example, how did Hugo decide that the first page would use the list.html template?

**Comment by jeffcsauer** [comment]
Late bump but still interested, particularly option 2 if @zayuim ever reached a solution!

**Comment by hongtaoh** [comment]
To remove the list from the homepage, in  [hugo-xmin/layouts/_default/list.html ](https://github.com/yihui/hugo-xmin/blob/master/layouts/_default/list.html), try :

```html
<ul>
  {{ $pages := .Pages }}
  {{ if .IsHome }}{{ $pages = .Site.RegularPages }}{{ end }}
  {{ if not .IsHome}}  <!-- add this line -->
  {{ range (where $pages "Section" "!=" "") }}
  <li>
    <span class="date">{{ .Date.Format "2006/01/02" }}</span>
    <a href="{{ .RelPermalink }}">{{ .Title | markdownify }}</a>
  </li>
  {{ end }}
  {{ end }} <!-- add this line -->
</ul> 
```

**Comment by zayuim** [comment]
@hongtaoh Thanks, I'll close the thread now.
