### ISSUE TITLE
error building theme

### ISSUE THREAD

**Issue by jkanche** [yihui/hugo-xmin#38]
I'm having issues building this theme any help would be appreciated! thank you!

> :> hugo serve
> Building sites … ERROR 2019/09/19 21:30:28 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:8:21: executing "_default/terms.html" at <.Page.RelPermalink>: can't evaluate field Page in type hugolib.WeightedPages

**Comment by jkanche** [comment]
works after updating hugo! thanks!

**Comment by thestatsguy** [comment]
Having the issue with the same error while using Netlify.. full Netlify deploy log also attached. Any advise would be deeply appreciated - thanks! 

`10:10:42 PM: Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/opt/build/repo/themes/hugo-xmin/layouts/_default/terms.html:8:21": execute of template failed: template: _default/terms.html:8:21: executing "_default/terms.html" at <.Page.RelPermalink>: can't evaluate field Page in type hugolib.WeightedPages
`
[netlify_log.txt](https://github.com/yihui/hugo-xmin/files/4558925/netlify_log.txt)

**Comment by mwasilak** [comment]
Please try specifying `HUGO_VERSION` environment variable in Netlify console (same as your local hugo version).
