### ISSUE TITLE
Jump to next post

### ISSUE THREAD

**Issue by jthaman** [yihui/hugo-xmin#43]
Yihui, can you give me some tips on modifying your theme? I'd like to put a link in the footer of each blog post that jumps to the next/previous blog post.

**Comment by yihui** [comment]
https://github.com/rbind/yihui/blob/378e27e54787c3c57ac906fd00143c7d1dc98cb3/layouts/partials/foot_custom.html#L2-L5

**Comment by jthaman** [comment]
Worked like a charm :)
