### ISSUE TITLE
where is the config.toml file

### ISSUE THREAD

**Issue by susanasarmento** [yihui/hugo-xmin#47]
Dear Xie
I read the blogdown book I read the recent updates on https://www.r-bloggers.com/2021/01/announcing-blogdown-v1-0/ and congratulations and thank you!
I was going to try out your theme Xmin (latest version), but I cannot find the config.toml file, not even in the ExampleSite directory. I thought you recommended using the  config.toml instead of  config.yaml, is that recommendation not applicable anymore?
Sorry if this is a silly question. Thank you so much for your receptivity and your excellent work.

EDIT: Ok converted the YAML file into TOML using this site https://www.convertsimple.com/convert-yaml-to-toml/ and carefully reading. Thank you silly problem is solved.

**Comment by yihui** [comment]
Right. I'm using `config.yaml`: https://github.com/yihui/hugo-xmin/blob/master/exampleSite/config.yaml

I don't remember I recommended TOML anywhere. If I did, I'd take the words back. I'm not satisfied with either TOML or YAML. I think YAML has had enough woes, and TOML is nowhere better.

BTW, `blogdown::yaml2toml()` can also help you convert YAML to TOML.

**Comment by kamaulindhardt** [comment]
..for some reason my blowdown site opens up with a configYAML instead of a config.TOLM, anyone an idea how I can solve this?

**Comment by yihui** [comment]
@kamaulindhardt It's not a problem, and I'm not sure what you are trying to solve. Hugo and **blogdown** support both formats.
