### ISSUE TITLE
好喜欢这个主题！

### ISSUE THREAD

**Issue by liutiming** [yihui/hugo-xmin#49]
打扰了，但我不知道在哪里可以表达我的喜爱 xx

**Comment by yihui** [comment]
这么朴素的主题，连我自己都不敢用，而真敢用这个主题的人，我们成为朋友的概率更大，目前我有印象的只有两位壮士：

1. @shrektan https://shrektan.com 
2. @deadfate-sky https://deadfate.rbind.io

**Comment by liutiming** [comment]
让我们做朋友吧哈哈! 昨天刚搭了一个小站https://timingliu.netlify.app

就像我在About里面说的：

> To me, each person should have a office that undergone frequent renovation to show the best outlook, but also a temple that stays as it is.

这个主题让人感觉很舒服，而且在技术上也让人对blogdown/hugo有了更好的理解，达到了技术，哲学，艺术三者合一的高度。
