### ISSUE TITLE
Where to put a favicon?

### ISSUE THREAD

**Issue by hanowell** [yihui/hugo-xmin#50]
I've tried putting a favicon in:

1. The root directory
2. A subdirectory of root called "static"
3. The static subdirectory within themes

The favicon doesn't display in any of these cases.

**Comment by yihui** [comment]
2 should work, if your favicon is named `favicon.ico` (and truly in the `.ico` format). If you want to use other images as the icon, you will have to customize `header.html` or `head_custom.html`: https://github.com/yihui/hugo-xmin/tree/master/layouts/partials

**Comment by hanowell** [comment]
I've confirmed this is an .ico format file and moved it back to static subdirectory of root. After Netlify build is complete, I'll clear my cache and restart my computer to see if the icon is displayed.

**Comment by hanowell** [comment]
Issue resolved. Must have been some kind of caching thing.
