### ISSUE TITLE
Broken Link to A.Hill Tutorial

### ISSUE THREAD

**Issue by mccurcio** [yihui/hugo-xmin#53]
The 2 links on:
https://xmin.yihui.org/note/2017/06/14/another-note/
1.  an awesome tutorial 
2. Allison's Blogdown tutorial 
give 404.

I would be interested to see the tutorial. ;)
Thanks

**Comment by yihui** [comment]
It has been moved to https://www.apreshill.com/blog/2020-12-new-year-new-blogdown/. I just fixed the links. Thanks!
