### ISSUE TITLE
inline footnotes no longer working

### ISSUE THREAD

**Issue by apalbright** [yihui/hugo-xmin#64]
I've been using xmin for my blogdown theme since 2018. I recently updated the theme files because the 2019 version was no longer deploying the netlify correctly, but now my inline footnotes no longer work.

[Here](https://thelittledataset.com/2022/03/21/job-mkt/) is an example page and you can see "^[]" in the text instead of footnotes.

So, I decided to test inline footnote functionality by generating a new xmin site and testing off of that. (I.e., all I did was make a new Rproj and then run `blogdown::new_site(theme = "yihui/hugo-xmin")`). Inline footnotes do not work when testing. See below screencap.
<img width="1759" alt="inline" src="https://github.com/yihui/hugo-xmin/assets/11253102/fbb46da6-126e-4063-b867-829a4af0e2ff">

However, regular footnotes do. See below screencap.
<img width="1759" alt="regular" src="https://github.com/yihui/hugo-xmin/assets/11253102/be9b7393-da22-43ba-9264-ccb7ff30505c">

Is there a way to get inline footnotes working again with xmin? Thanks for your help!

**Comment by apalbright** [comment]
Ah, I am now thinking this is an issue due to newer Hugo versions. I see your post about inline footnotes no longer working with newer Hugo [here](https://yihui.org/en/2023/02/markdown-footnotes/). 

Is that correct? If so, feel free to just close this issue.

I'll be converting my inline footnotes to regular then! Thanks.

**Comment by yihui** [comment]
> Ah, I am now thinking this is an issue due to newer Hugo versions.

Yes.
