### ISSUE TITLE
Add direct link to demosite on themes.gohugo.io

### ISSUE THREAD

**Issue by leoheitmannruiz** [yihui/hugo-xmin#69]
Hey,
I'm not interested in singing a CLA so I'll open an issue:

At https://themes.gohugo.io/themes/hugo-xmin/ there is no direct link to the demo site at https://xmin.yihui.org/.

Please add the demosite variable to theme.toml. See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration.

So that there is a "Demo" button, like at https://themes.gohugo.io/themes/hugo-book/.

Would be very much appreciated!

**Comment by yihui** [comment]
Great suggestion! Thank you!
