### ISSUE TITLE
Please change the default baseURL

### ISSUE THREAD

**Issue by frjo** [yihui/hugo-xmin#71]
Please change this to something like `https://example.org/`. In the Hugo forums we get large number of new users that get in to trouble because they keep this example setting.

https://github.com/yihui/hugo-xmin/blob/b76b60eb943627a8d763e6095c19561315140f69/exampleSite/hugo.yaml#L1

**Comment by frjo** [comment]
These are some of the problems you get:

1. The `hugo server` command will output `Web Server is available at //localhost:1313/ (bind address 127.0.0.1) `. See the schema less adress for the dev server.
2. No full URLs can be created, `<link rel="canonical" href="/">` is e.g. not correct for the front page. It should be `<link rel="canonical" href="https://example.org/">`.
3. When you deploy the site to be served in a sub dir, e.g. `https://example.org/docs/` no resources, i.e. css/js/images/, will be loaded.
4. Things like image in the RSS feed will have incorrect URLs.

**Comment by yihui** [comment]
Done. Thanks!

**Comment by chuxinyuan** [comment]
https://example.com/ 更具一般性。

**Comment by yihui** [comment]
这两个域名并没有实质性区别。

**Comment by frjo** [comment]
Thanks!
