### ISSUE TITLE
Using a js from your server?

### ISSUE THREAD

**Issue by jflycn** [yihui/hugo-xmin#9]
I see this code at the bottom of every page:

`<script async src="//yihui.name/js/center-img.js"></script>`

**Comment by jflycn** [comment]
OK. Just found out it is from "\layouts\partials\foot_custom.html" .

I guess it was copied over from the "exampleSite" folder when the theme was installed.

**Comment by yihui** [comment]
That is right. It is up to you whether you want to use it. It is not part of the core theme.
